# Generated by Django 4.2.6 on 2024-01-21 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_request_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='user_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='account.bank_detail'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='votes',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_vote', to='account.plan'),
        ),
        migrations.AddField(
            model_name='votes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_plan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_plan', to='account.plan'),
        ),
        migrations.AddField(
            model_name='user_plan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='income',
            name='refer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='income',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='income',
            name='user_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_plan', to='account.user_plan'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='account.deposit_image'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposit_request_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bank_detail',
            name='bank_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.add_bank'),
        ),
        migrations.AddField(
            model_name='bank_detail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bank_detail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='votes',
            unique_together={('plan', 'user')},
        ),
    ]
