# Generated by Django 4.2.6 on 2024-01-21 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Withdraw Success', 'Withdraw Success'), ('Withdraw Failed', 'Withdraw Failed'), ('Recharge Success', 'Recharge Success'), ('Recharge Failed', 'Recharge Failed'), ('Withdraw Request', 'Withdraw Request'), ('Recharge Request', 'Recharge Request')], max_length=100)),
                ('user_number', models.CharField(blank=True, max_length=200, null=True)),
                ('notification_body', models.TextField()),
                ('is_open', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'notifications',
                'db_table': 'notification',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
